FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /aspnet

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:7.0
COPY --from=build /app /
EXPOSE 80
ENTRYPOINT ["dotnet", "/ChatbotBackend.dll"]